version: "3.8"

services:
  log-server-http:
    build:
      context: .
    container_name: log-server-http
    command: ["http", "${HTTP_PORT:-8080}"]
    ports:
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"

  log-server-https:
    build:
      context: .
    container_name: log-server-https
    command: ["https", "${HTTPS_PORT:-8443}"]
    ports:
      - "${HTTPS_PORT:-8443}:${HTTPS_PORT:-8443}"
    volumes:
      - ./certs:/home/node/certs

  log-server-tcp:
    build:
      context: .
    container_name: log-server-tcp
    command: ["tcp", "${TCP_PORT:-4444}"]
    ports:
      - "${TCP_PORT:-4444}:${TCP_PORT:-4444}"
